//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_tbl
    {
        public int ADMIN_ID { get; set; }
        public string ADMIN_USERNAME { get; set; }
        public string ADMIN_PASSWORD { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
