//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT_TBL
    {
        public int DISTRICT_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
        public Nullable<int> STATE_ID { get; set; }
    
        public virtual STATE_TBL STATE_TBL { get; set; }
    }
}
