//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRICT_MASTER()
        {
            this.customer_tbl = new HashSet<customer_tbl>();
            this.user_tbl = new HashSet<user_tbl>();
        }
    
        public int DISTRICT_ID { get; set; }
        public string DISTRCT_NAME { get; set; }
        public Nullable<int> STATE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_tbl> customer_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_tbl> user_tbl { get; set; }
    }
}
