//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sri123_mbdbEntities : DbContext
    {
        public sri123_mbdbEntities()
            : base("name=sri123_mbdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<admin_tbl> admin_tbl { get; set; }
        public virtual DbSet<user_collections_tbl> user_collections_tbl { get; set; }
        public virtual DbSet<customer_tbl> customer_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
    }
}
