//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_collections_tbl
    {
        public int COLLECTION_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public double AMOUNT { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int USER_ID { get; set; }
    }
}
