//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tbl_TMP
    {
        public int USER_ID { get; set; }
        public string USER_PASSWORD { get; set; }
        public string NAME { get; set; }
        public string USER_MOBILENO { get; set; }
        public string USER_MAIL_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string IS_ACTIVE { get; set; }
        public string USER_TYPE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string FATHER_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ADDHAR_NO { get; set; }
        public string PAN_NO { get; set; }
        public string USER_GUID { get; set; }
        public string STATE { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public Nullable<int> PINCODE { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string PASSPORT_SIZE_PHOTO { get; set; }
    }
}
